name: example_project
description: example

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  bpac_dart:
    path: ../
  flutter:
    sdk: flutter
  http: ^1.3.0
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  