name: bpac_dart
description: A starting point for Dart libraries or applications.
version: 0.1.0
repository: https://github.com/bjwe/bpac-dart

environment:
  sdk: ^3.6.1

dependencies:
  ffi: ^2.1.3
  shelf_router: ^1.1.4
  shelf_static: ^1.1.3
  win32: ^5.10.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
